name: easy_audio_player
description: an easy widgets to  have audio player that can play remote or local audio files across all platforms without having to implement it from scratch.
version: 0.0.1
homepage: https://github.com/egyleader/easy_audio_player.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.6+1
  audio_video_progress_bar: ^0.10.0
  just_audio: ^0.9.18
  just_audio_background: ^0.0.1-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

